In [175]:
import numpy as np
from sklearn import datasets
import random,operator
iris = datasets.load_iris()

iris_data = iris.data
iris_labels = iris.target

np.random.seed(42)
indices = np.random.permutation(len(iris_data))

Numberofsample = 38
learndataset = iris_data[indices[:-Numberofsample]]
learndatasetLabels = iris_labels[indices[:-Numberofsample]]

Testdata = iris_data[indices[-Numberofsample:]]
TestdataLabels = iris_labels[indices[-Numberofsample:]]

In [176]:
def distance(instance1,instance2):
	instance1 = np.array(instance1)
	instance2 = np.array(instance2)
	return np.linalg.norm(instance1-instance2)

In [177]:
def get_neighbour(TrainData,TrainLabels,TestInstance,k,distance=distance):
	distances=[]
	for i in range(len(TrainData)):
		dist = distance(TestInstance,TrainData[i])
		#distances.append(np.array(TrainData[i],dist,TrainLabels[i]))
		distances.append((TrainData[i],dist,TrainLabels[i]))
		distances.sort(key=lambda x:x[1]) # sorting as per distance which is X[1] X[0] is trainingdata
		neighbors = distances[:k] # everything upto k 
	return neighbors

In [178]:
def getresponse(neighbors):
	classvotes = {}
	for x in range(len(neighbors)):
		response = neighbors[x][-1]
		if response in classvotes:
			classvotes[response] += 1
		else :
			classvotes[response] = 1
	sortedvotes = sorted(classvotes.items(), key=operator.itemgetter(1),reverse=True)
	return sortedvotes[0][0]

In [179]:
#TestInstance = [[7.2, 3.6, 5.1, 2.5]]
#import pandas as pd
#test = pd.DataFrame(TestInstance)
k = 5

In [180]:
neigh = get_neighbour(learndataset,learndatasetLabels,Testdata[4],k)
neigh

[(array([5.7, 2.9, 4.2, 1.3]), 0.3000000000000001, 1),
 (array([6. , 2.9, 4.5, 1.5]), 0.33166247903553975, 1),
 (array([5.7, 3. , 4.2, 1.2]), 0.36055512754639907, 1),
 (array([6.2, 2.9, 4.3, 1.3]), 0.3872983346207415, 1),
 (array([5.6, 3. , 4.5, 1.5]), 0.4242640687119289, 1)]

In [181]:
result = getresponse(neigh)
result

1

In [182]:
TestdataLabels[9]

0

In [183]:
results=[]
for ix in range(len(Testdata)):
    neigh = get_neighbour(learndataset,learndatasetLabels,Testdata[ix],k)
    results.append(getresponse(neigh))
np.mean(results==TestdataLabels)

0.9736842105263158